const allInterests = [
    'Reading',
    'Writing',
    'Cooking',
    'Baking',
    'Traveling',
    'Hiking',
    'Running',
    'Yoga',
    'Meditation',
    'Painting',
    'Drawing',
    'Photography',
    'Videography',
    'Music',
    'Playing instruments',
    'Singing',
    'Dancing',
    'Acting',
    'Poetry',
    'Theater',
    'Gaming',
    'Board games',
    'Puzzles',
    'Science fiction',
    'Fantasy',
    'Technology',
    'Coding',
    'Robotics',
    'Astronomy',
    'Mathematics',
    'History',
    'Geography',
    'Sports (e.g., soccer, basketball, tennis)',
    'Martial arts',
    'Volunteering',
    'Environmentalism',
    'Gardening',
    'DIY crafts',
    'Fashion',
    'Makeup artistry',
    'Podcasting',
    'Blogging',
    'Vlogging',
    'Languages and linguistics',
    'Cultural studies',
    'Debate',
    'Model UN',
    'Entrepreneurship',
    'Investing',
    'Personal finance',
    'Self-improvement',
    'Fitness',
    'Nutrition',
    'Mental health awareness',
    'Social justice',
    'Animal rights',
    'Bird watching',
    'Fishing',
];

const allSortedInterests = allInterests.sort((a, b) => a.localeCompare(b));

export default allSortedInterests;